// Downloads a handful of acoustic-grand-piano note samples and embeds them,
// base64-encoded, into js/data/piano-samples.js so the app has a real piano
// sound that works offline from file:// (no runtime fetch).
//
// Source: FluidR3_GM acoustic grand piano (MIT-licensed soundfont) via
// gleitz/midi-js-soundfonts. Run once: node tools/fetch-piano.mjs
import { writeFile } from 'node:fs/promises';
import path from 'node:path';

const BASE = 'https://gleitz.github.io/midi-js-soundfonts/FluidR3_GM/acoustic_grand_piano-mp3';

// Anchors every 4 semitones spanning the corpus range C2(36)..A5(81).
// Max pitch-shift to any target is +/- 2 semitones — good piano fidelity.
const ANCHORS = [
  ['C2', 36], ['E2', 40], ['Ab2', 44], ['C3', 48], ['E3', 52], ['Ab3', 56],
  ['C4', 60], ['E4', 64], ['Ab4', 68], ['C5', 72], ['E5', 76], ['Ab5', 80],
];

const samples = {};
let totalKB = 0;
for (const [name, midi] of ANCHORS) {
  const res = await fetch(`${BASE}/${name}.mp3`);
  if (!res.ok) throw new Error(`fetch ${name} failed: ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  samples[midi] = buf.toString('base64');
  totalKB += buf.length / 1024;
  console.log(`${name} (midi ${midi})  ${(buf.length / 1024).toFixed(0)} KB`);
}

const out = path.join(import.meta.dirname, '..', 'js', 'data', 'piano-samples.js');
const banner = `// Generated by tools/fetch-piano.mjs — do not edit by hand.
// Acoustic grand piano samples from the FluidR3_GM soundfont
// (https://github.com/gleitz/midi-js-soundfonts), MIT-licensed, embedded as
// base64 MP3 so the app's piano sound works offline. Keyed by MIDI note.
`;
await writeFile(out, `${banner}window.DS_PIANO = { format: 'mp3', samples: ${JSON.stringify(samples)} };\n`);
console.log(`\nwrote ${out}  (~${totalKB.toFixed(0)} KB raw, ${(JSON.stringify(samples).length / 1024).toFixed(0)} KB base64)`);
